# Generated by Django 3.2.8 on 2021-12-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('mfr', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=15)),
                ('purchased_date', models.DateField()),
                ('date_sold', models.DateField()),
                ('fuel_type', models.CharField(max_length=15)),
                ('features', models.CharField(max_length=100)),
                ('number_of_doors', models.CharField(max_length=15)),
                ('rowseat', models.IntegerField()),
                ('transmission', models.CharField(max_length=20)),
            ],
        ),
    ]
