# Generated by Django 3.2.8 on 2021-12-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_of_doors',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6')], max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rowseat',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Truck', 'Truck'), ('SUV', 'SUV'), ('Bus', 'Bus'), ('Collection', 'Collection')], max_length=15),
        ),
    ]
