# Generated by Django 3.2.9 on 2021-12-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20211202_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='number_of_doors',
            field=models.IntegerField(choices=[(2, 2), (4, 4), (6, 6)], default=4),
        ),
    ]
