# Generated by Django 3.2.9 on 2021-12-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_vehicle_number_of_doors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
    ]
