# Generated by Django 3.2.8 on 2021-12-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20211212_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='millage',
            field=models.IntegerField(blank=True, default=50000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='main_image',
            field=models.ImageField(blank=True, default='/sample.jpg', null=True, upload_to='images'),
        ),
    ]
