# Generated by Django 3.2.8 on 2021-12-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20211214_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='%m/%d/%Y %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchased_date',
            field=models.DateField(verbose_name='%m/%d/%Y'),
        ),
    ]
