# Generated by Django 3.2.8 on 2021-12-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20211215_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchased_date',
            field=models.DateField(),
        ),
    ]
